{
 "title": "Shopping Cart - Resource Usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Load Balancer CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"shopping-cart\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-loadbalancer\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Service CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"shopping-cart\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-service\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Database CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"shopping-cart\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-database-deployment\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"shopping-cart\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-loadbalancer\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Service Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"shopping-cart\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-service\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Database Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"shopping-cart\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"shopping-cart\", workload=\"store-database-deployment\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-loadbalancer\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Service Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-service\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Database Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-database-deployment\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-loadbalancer\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Service Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-service\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Database Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=~\"shopping-cart\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"shopping-cart\", workload=~\"store-database-deployment\", workload_type=\"deployment\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}