{
 "title": "Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Load Balancer Processed connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"nginx-exporter-service:9113\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"nginx-exporter-service:9113\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"nginx-exporter-service:9113\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"nginx-exporter-service:9113\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"nginx-exporter-service:9113\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"nginx-exporter-service:9113\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "gauge",
   "description": "Response Time P95",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (gin_request_duration_sum) / sum(gin_request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request Duration P 95",
   "type": "gauge",
   "description": "Response Time P95",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Response Time P 99",
   "type": "gauge",
   "description": "Response Time P99",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rate(gin_request_total[5m])" }
   ]
  },
  {
   "title": "PV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "UV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_uv_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum) / sum(gin_request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Product List Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/product\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/product\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{uri=\"/api/v1/product\"}) / sum(gin_request_duration_count{uri=\"/api/v1/product\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Product Detail Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/product/:id\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/product/:id\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{uri=\"/api/v1/product/:id\"}) / sum(gin_request_duration_count{uri=\"/api/v1/product/:id\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Order Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/order\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/order\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{uri=\"/api/v1/order\"}) / sum(gin_request_duration_count{uri=\"/api/v1/order\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Confirm Payment Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/confirmPayment\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{uri=\"/api/v1/confirmPayment\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{uri=\"/api/v1/confirmPayment\"}) / sum(gin_request_duration_count{uri=\"/api/v1/confirmPayment\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_body_total[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(gin_response_body_total[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(method, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{method}}"
    }
   ]
  },
  {
   "title": "Slow Request(default 5s)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (gin_slow_request_total)",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(code, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{code}}"
    }
   ]
  }
 ]
}