apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-service
spec: 
  type: ClusterIP
  selector:
    app: mysqld-exporter
  ports: 
    - protocol: TCP
      port: 9104
      targetPort: 9104