apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
spec: 
  type: ClusterIP
  selector:
    app: nginx-exporter
  ports: 
    - protocol: TCP
      port: 9113
      targetPort: 9113