version: "3.5"

services:
  store-service:
    image: sckseal/toy-store-service:0.0.3
    container_name: store-service
    ports:
      - "8000:8000"
    depends_on:
      - store-database
    restart: always
    environment: 
      - TEST_MODE=true
    
  store-cache:
    image: redis:latest
    container_name: store-cache
    ports: 
    - "6379:6379"

  store-database:
    image: mysql:5.7
    container_name: store-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sealteam
      - MYSQL_PASSWORD=sckshuhari
      - MYSQL_DATABASE=toy
    volumes:
      - ./tearup/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  # store-database-cluster:
  #   image: mysql/mysql-cluster:5.7
  #   container_name: store-database
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=sealteam
  #     - MYSQL_PASSWORD=sckshuhari
  #     - MYSQL_DATABASE=toy
  #   volumes:
  #     - ./tearup/:/docker-entrypoint-initdb.d/
  #   ports:
  #     - "3306:3306"

  store-web:
    image: sckseal/toy-store-web:0.0.2
    container_name: store-web
    ports:
      - "3000:3000"

  store-nginx:
    image: sckseal/toy-store-nginx:0.0.2
    container_name: store-nginx
    restart: always
    depends_on:
      - store-service
      - store-web
    ports:
      - "80:80"

  bank-gateway:
    image: sckseal/toy-store-bankgateway:0.0.1
    container_name: bank-gateway
    restart: always
    ports:
      - "8882:8882"

  shipping-gateway:
    image: sckseal/toy-store-shippinggateway:0.0.1
    container_name: shipping-gateway
    restart: always
    ports:
      - "8883:8882"