apiVersion: v1
kind: Service
metadata:
  name: shipping-gateway
spec: 
  type: ClusterIP
  selector:
    app: shipping-gateway
  ports: 
    - protocol: TCP
      port: 8882
      targetPort: 8882
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shipping-gateway
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: shipping-gateway
  template:
    metadata: 
      labels: 
        app: shipping-gateway
    spec:
      restartPolicy: Always
      containers:
      - image: sckseal/toy-store-shippinggateway:0.0.1
        name:  shipping-gateway
        ports:
        - containerPort: 8882
        
