apiVersion: apps/v1
kind: Deployment
metadata: 
  name: store-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata: 
      labels: 
        app: store-service
    spec:
      restartPolicy: Always
      containers:
      - image: sckseal/toy-store-service:0.0.4
        name:  store-service
        ports:
        - containerPort: 8000
        env:
        - name: TEST_MODE
          value: "true"
        #- name: CACHE_ON
        #  value: "true"
